// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyDgec7-empdz9aPMlTpcCdlqp4d-Stys',
    appId: '1:127038696297:web:2e03f496eb037155caebf8',
    messagingSenderId: '127038696297',
    projectId: 'fashion-find-14a06',
    authDomain: 'fashion-find-14a06.firebaseapp.com',
    storageBucket: 'fashion-find-14a06.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRkOd97KJdq-ENvxmbRe75kTcOFewcFOk',
    appId: '1:127038696297:android:f26223634a36ec59caebf8',
    messagingSenderId: '127038696297',
    projectId: 'fashion-find-14a06',
    storageBucket: 'fashion-find-14a06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOrlcLtcPfNlzbzoBtT5Re8iNTglIu4Gg',
    appId: '1:127038696297:ios:f67a0107e0aa4381caebf8',
    messagingSenderId: '127038696297',
    projectId: 'fashion-find-14a06',
    storageBucket: 'fashion-find-14a06.firebasestorage.app',
    iosBundleId: 'com.example.fashionFind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOrlcLtcPfNlzbzoBtT5Re8iNTglIu4Gg',
    appId: '1:127038696297:ios:f67a0107e0aa4381caebf8',
    messagingSenderId: '127038696297',
    projectId: 'fashion-find-14a06',
    storageBucket: 'fashion-find-14a06.firebasestorage.app',
    iosBundleId: 'com.example.fashionFind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyDgec7-empdz9aPMlTpcCdlqp4d-Stys',
    appId: '1:127038696297:web:0611227d5d42575fcaebf8',
    messagingSenderId: '127038696297',
    projectId: 'fashion-find-14a06',
    authDomain: 'fashion-find-14a06.firebaseapp.com',
    storageBucket: 'fashion-find-14a06.firebasestorage.app',
  );
}
